spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?useSSL=false
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    database: postgresql
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres?useSSL=false
    schemas: betapp
    user: postgres
    password: password

scheduler:
  enabled: true
  duration:
    match-result-task: 5
    odds-task: 60

betapp:
  footballdata:
    url: "http://api.football-data.org"
    apiKey: "2012103e35f84b5eaf52686ee0ae34dc"
  theoddsapi:
    url: "https://api.the-odds-api.com"
    apikey: "eb610dd26d7b371a91703917f6100d84"
    competitionKey:
      CL: "soccer_uefa_champs_league"
      FL1: "soccer_france_ligue_one"
      PD: "soccer_spain_la_liga"
      BL1: "soccer_germany_bundesliga"
      PL: "soccer_epl"
      SA: "soccer_italy_serie_a"


