spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?useSSL=false
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    database: postgresql
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres?useSSL=false
    schemas: betapp
    user: postgres
    password: password

scheduler:
  enabled: true
  duration:
    match-result-task: 5

betapp:
  url:
    footballdata: "http://api.football-data.org"
    theoddsapi: "https://api.the-odds-api.com"

  apikey:
    footballdata: "2012103e35f84b5eaf52686ee0ae34dc"
    theoddsapi: "eb610dd26d7b371a91703917f6100d84"
