INSERT INTO betapp.team(code, name, flag) VALUES
('QAT', 'QATAR', 'https://crests.football-data.org/8030.svg'),
('ECU', 'ECUADOR', 'https://crests.football-data.org/791.svg'),
('SEN', 'SENEGAL', 'https://crests.football-data.org/senegal.svg'),
('NED', 'NETHERLANDS', 'https://crests.football-data.org/8601.svg'),
('ENG', 'ENGLAND', 'https://crests.football-data.org/770.svg'),
('IRN', 'IR IRAN', 'https://crests.football-data.org/iran.svg'),
('USA', 'USA', 'https://crests.football-data.org/usa.svg'),
('WAL', 'WALES', 'https://crests.football-data.org/833.svg'),
('ARG', 'ARGENTINA', 'https://crests.football-data.org/762.png'),
('KSA', 'SAUDI ARABIA', 'https://crests.football-data.org/saudi_arabia.svg'),
('MEX', 'MEXICO', 'https://crests.football-data.org/mexico.svg'),
('POL', 'POLAND', 'https://crests.football-data.org/794.svg'),
('FRA', 'FRANCE', 'https://crests.football-data.org/773.svg'),
('AUS', 'AUSTRALIA', 'https://crests.football-data.org/779.svg'),
('DEN', 'DENMARK', 'https://crests.football-data.org/782.svg'),
('TUN', 'TUNISIA', 'https://crests.football-data.org/tunisia.svg'),
('ESP', 'SPAIN', 'https://crests.football-data.org/760.svg'),
('CRC', 'COSTA RICA', 'https://crests.football-data.org/costa_rica.svg'),
('GER', 'GERMANY', 'https://crests.football-data.org/759.svg'),
('JPN', 'JAPAN', 'https://crests.football-data.org/JAP.svg'),
('BEL', 'BELGIUM', 'https://crests.football-data.org/805.svg'),
('CAN', 'CANADA', 'https://crests.football-data.org/canada.svg'),
('MAR', 'MOROCCO', 'https://crests.football-data.org/morocco.svg'),
('CRO', 'CROATIA', 'https://crests.football-data.org/799.svg'),
('BRA', 'BRAZIL', 'https://crests.football-data.org/764.svg'),
('SRB', 'SERBIA', 'https://crests.football-data.org/780.svg'),
('SUI', 'SWITZERLAND', 'https://crests.football-data.org/788.svg'),
('CMR', 'CAMEROON', 'https://crests.football-data.org/cameroon.svg'),
('POR', 'PORTUGAL', 'https://crests.football-data.org/765.svg'),
('GHA', 'GHANA', 'https://crests.football-data.org/ghana.svg'),
('URU', 'URUGUAY', 'https://crests.football-data.org/758.svg'),
('KOR', 'KOREA REPUBLIC', 'https://crests.football-data.org/772.png');