INSERT INTO betapp.coach ("first_name", "last_name", "team_code")
VALUES ('Gustavo', 'Alfaro', 'ECU'),
       ('Louis', 'van Gaal', 'NED'),
       ('Felix', 'Sanchez', 'QAT'),
       ('Aliou', 'Cisse', 'SEN'),
       ('Gareth', 'Southgate', 'ENG'),
       ('Gregg', 'Berhalter', 'USA'),
       ('Carlos', 'Queiroz', 'IRN'),
       ('Rob', 'Page', 'WAL'),
       ('Lionel', 'Scaloni', 'ARG'),
       ('Gerardo', 'Martino', 'MEX'),
       ('Czeslaw', 'Michniewicz', 'POL'),
       ('Herve', 'Renard', 'KSA'),
       ('Graham', 'Arnold', 'AUS'),
       ('Kasper', 'Hjulmand', 'DEN'),
       ('Didier', 'Deschamps', 'FRA'),
       ('Jalel', 'Kadri', 'TUN'),
       ('Luis', 'Suarez', 'CRC'),
       ('Hansi', 'Flick', 'GER'),
       ('Hajime', 'Moriyasu', 'JPN'),
       ('Luis', 'Enrique', 'ESP'),
       ('Roberto', 'Martinez', 'BEL'),
       ('John', 'Herdman', 'CAN'),
       ('Zlatko', 'Dalic', 'CRO'),
       ('Walid', 'Regragui', 'MAR'),
       ('', 'Tite', 'BRA'),
       ('Rigobert', 'Song', 'CMR'),
       ('Dragan', 'Stojkovic', 'SRB'),
       ('Murat', 'Yakin', 'SUI'),
       ('Otto', 'Addo', 'GHA'),
       ('Fernando', 'Santos', 'POR'),
       ('Paulo', 'Bento', 'KOR'),
       ('Diego', 'Alonso', 'URU');